/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDetalhesAcomodacao.java
 *
 * Created on 16/10/2012, 13:20:53
 */
package view;

import controller.ColaboradorController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;

import javax.swing.JInternalFrame;

import model.Acomodacao;
import model.Colaborador;

/**
 *
 * @author glauberc
 */
public class FormDetalhesAcomodacao extends JInternalFrame {
    
    private Acomodacao acomodacao;

    /** Creates new form FormDetalhesAcomodacao */
    public FormDetalhesAcomodacao(Acomodacao acomodacao) {
        initComponents();
        this.acomodacao = acomodacao;
        this.populateText();
        this.requestFocus();
    }
    
    private void populateText(){
    	this.setTitle("Liberação de Acesso");
		this.setSize(700, 750);
		this.setClosable(true);
		this.setMaximizable(true);

        ColaboradorController cc = new ColaboradorController();
        Colaborador colaborador = new Colaborador();
        colaborador.setId(this.acomodacao.getIdColaborador());
        colaborador = cc.detalhar(colaborador);
        
        
        String NEW_LINE = System.getProperty("line.separator");
        
        
        this.txtDetalhes.append("Nome do Responsável: "+colaborador.getNome()+NEW_LINE);        
        this.txtDetalhes.append("Email do Responsável: "+colaborador.getEmail()+NEW_LINE+NEW_LINE);
        
        this.txtDetalhes.append("Acomodação:"+NEW_LINE+NEW_LINE);
        String simNao = this.acomodacao.isCafe()?"Sim":"Não";
        this.txtDetalhes.append("Café da manhã incluso?: "+simNao+NEW_LINE);
        this.txtDetalhes.append("Endereço: "+this.acomodacao.getEndereco()+NEW_LINE);        
        this.txtDetalhes.append("Endereço: "+this.acomodacao.getEndereco()+NEW_LINE);
        this.txtDetalhes.append("Valor da Diária: "+this.acomodacao.getValorDiario()+NEW_LINE);
        this.txtDetalhes.append("Descrição: "+this.acomodacao.getDescricao()+NEW_LINE);
        
        this.GoogleMaps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.GoogleMaps.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                try {
                    URI uri = new URI("http://maps.google.com.br/maps?hl=pt-BR&ll=-28.772474,-52.371826");
                    desktop.browse(uri);
                }catch(Exception exc){}
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelTxtDetalhes = new javax.swing.JScrollPane();
        txtDetalhes = new javax.swing.JTextArea();
        GoogleMaps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDetalhes.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtDetalhes.setColumns(20);
        txtDetalhes.setEditable(false);
        txtDetalhes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDetalhes.setLineWrap(true);
        txtDetalhes.setRows(5);
        scrollPanelTxtDetalhes.setViewportView(txtDetalhes);

        GoogleMaps.setForeground(java.awt.Color.blue);
        GoogleMaps.setText("Clique aqui para ver a localização");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelTxtDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoogleMaps)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPanelTxtDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoogleMaps)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GoogleMaps;
    private javax.swing.JScrollPane scrollPanelTxtDetalhes;
    private javax.swing.JTextArea txtDetalhes;
    // End of variables declaration//GEN-END:variables
}
